"""add period to indicator_values

Revision ID: 3ae6098a6441
Revises: cf26acb84ff9
Create Date: 2026-01-08 13:19:49.357376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae6098a6441'
down_revision: Union[str, Sequence[str], None] = 'cf26acb84ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_values', sa.Column('period', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('uq_indicator_region_year'), 'indicator_values', type_='unique')
    op.create_unique_constraint('uq_indicator_region_year', 'indicator_values', ['indicator_id', 'region_id', 'year', 'period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_indicator_region_year', 'indicator_values', type_='unique')
    op.create_unique_constraint(op.f('uq_indicator_region_year'), 'indicator_values', ['indicator_id', 'region_id', 'year'], postgresql_nulls_not_distinct=False)
    op.drop_column('indicator_values', 'period')
    # ### end Alembic commands ###
