"""extend region code to 11 chars

Revision ID: cf26acb84ff9
Revises: 9fc7597ef6d7
Create Date: 2026-01-06 13:46:35.940785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf26acb84ff9'
down_revision: Union[str, Sequence[str], None] = '9fc7597ef6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'code',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
